//! exit_code: 1
fn* gen() -> Coroutine<()> {
    defer {
        yield  // diag: error(yield_in_defer): "cannot yield inside a defered expression"
    }
}

fn main() {
    gen();
}
